### ISSUE TITLE
`dynamic` bad

### ISSUE THREAD

**Issue by john-h-k** [spec-tacles/Spectacles.NET#1]
Unless there is a *very* good reason for it, using dynamic is really bad. Don't use it. Prefer using an abstract base class to represent the common methods needed.

dynamic is bad for productivity (compile time errors, well, lack of them), and is really slow. Really slow

**Comment by DevYukine** [comment]
Fixed in 1ffe6e36bbf897c7760aad44673d44e937ba0c1a
